Repository AY2223S1-CS2103T-F12-3/tp, pull requests merged in 2022-10, with the labels that each got.

#26 Update project README and _config.yml
  README.md
  docs/_config.yml
Labels: documentation

#49 Updated UI for HelpWindow
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/NotioNUS.css
Labels: priority.Medium

#61 Enable assertions in gradle file
  build.gradle
Labels: priority.High

#62 Updated images and DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/user-guide/Ui.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/NotionUS.css
  src/main/resources/view/NotionUSMainWindow.fxml
Labels: documentation

#66 Update DG and diagram for mark and unmark feature.
  docs/DeveloperGuide.md
  docs/diagrams/MarkSequenceDiagram.puml
  docs/images/MarkSequenceDiagram.png
Labels: documentation

#68 Correct mistake in Model diagram
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: documentation, type.Bug

#70 Introduce default sorting of tasks
  src/main/java/seedu/address/model/task/Module.java
  src/main/java/seedu/address/model/task/Name.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniquePersonList.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/ListDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/ListMarkedCommandTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/model/task/ModuleTest.java
  src/test/java/seedu/address/model/task/NameTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#78 Formalize command format and update Quick Start
  docs/UserGuide.md
Labels: documentation

#81 update command format for UG
  docs/UserGuide.md
Labels: documentation

#82 add header for list and UG for archive
  docs/UserGuide.md
Labels: documentation

#79 Autocomplete feature and some updates to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/AutocompleteActivityDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/HideSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/MarkSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/AutocompleteActivityDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/HideSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/MarkSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/list/ListDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/list/ListMarkedCommand.java
  src/main/java/seedu/address/logic/commands/list/ListModuleCommand.java
  src/main/java/seedu/address/logic/commands/list/ListTagCommand.java
  src/main/java/seedu/address/logic/commands/list/ListUnmarkedCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/ModuleContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/fonts/roboto/Roboto-Thin.ttf
  src/main/resources/fonts/roboto/Roboto-ThinItalic.ttf
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/FilterStatusDisplay.fxml
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/task/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskByDeadlinePredicateTest.java
  src/test/java/seedu/address/model/task/TaskIsDonePredicateTest.java
Labels: documentation, priority.High

#83 Add introduction and acknowledgements for DG
  docs/DeveloperGuide.md
Labels: documentation

#89 Add tag command and tests for tag command.
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/testutil/EditPersonTagsBuilder.java
Labels: priority.Medium

#104 Fix Tag command replacing tags instead of adding tags.
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#180 Fix User Guide issues.
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#181 Updated UG and fixed ls -t
  docs/UserGuide.md
  docs/images/user-guide/Autocomplete.png
  docs/images/user-guide/FindCommandMultiple.png
  docs/images/user-guide/FindCommandSingular.png
  docs/images/user-guide/GUIwalkaround.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/list/ListNameCommand.java
  src/main/java/seedu/address/model/task/NameOrTagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/images/notionUS_logo.png
  src/main/resources/view/NotionUSMainWindow.fxml
  src/test/java/seedu/address/logic/commands/ListTagCommandTest.java
Labels: documentation, FunctionalityBug

#183 UG Updates
  docs/UserGuide.md
Labels: documentation
